
% grid
grid := 1;

% dot label
dot_label := 1;

% hints
hints := 1;
outputtemplate := "files/output-svg/%c.svg";
outputformat := "svg";

% global unity
u := 28.5pt;

% X Unity
ux := 1u;

% Y Unity
uy := 1u;

% Stroke Unity
s := 1u;

% X Stroke Unity
sx := 0.8s;

% Y Stroke Unity
sy := 0.8s;

% Stroke rotation
rot := 0;

% baseline
baseline := 17;

% xHeight
xHeight := 19   baseline;

% capHeight
capHeight := 10  us;