
% grid
grid := 0;

% dot label
dot_label := 0;

% hints
hints := 0;
outputtemplate := "files/output-svg/%c.svg";
outputformat := "svg";

% global unity
u := 12pt;

% X Unity
ux := 1u;

% Y Unity
uy := 1u;

% Stroke Unity
s := 1.5u;

% X Stroke Unity
sx := 2.15s;

% Y Stroke Unity
sy := 1s;

% Stroke rotation
rot := 267;

% baseline
baseline := 18;

% xHeight
xHeight := 14   baseline;

% capHeight
capHeight := 21  us;