
% grid
grid := 0;

% dot label
dot_label := 0;

% hints
hints := 1;
outputtemplate := "files/output-svg/%c.svg";
outputformat := "svg";

% global unity
u := 22.75pt;

% X Unity
ux := 1u;

% Y Unity
uy := 1u;

% Stroke Unity
s := 0.15u;

% X Stroke Unity
sx := 1s;

% Y Stroke Unity
sy := 1s;

% Stroke rotation
rot := 81;

% baseline
baseline := 19;

% xHeight
xHeight := 15   baseline;

% capHeight
capHeight := 21  us;